package csulb.cecs323.model;

import java.util.GregorianCalendar;

public class AlbumPK {
	
	private String title;
	private GregorianCalendar dateReleased;
	
	//empty constructor
	public AlbumPK() {}
	
	/**
	 * this function has the primary keys of Album
	 * @param title
	 * @param dateReleased
	 */
	public AlbumPK(String title, GregorianCalendar dateReleased) {
		this.title = title;
		this.dateReleased = dateReleased;
	}
	
	/**
	 * this function compares 2 "Albums"
	 */
	public boolean equals (Object object) {
		if (object instanceof AlbumPK) {
			AlbumPK pk = (AlbumPK)object;
			return this.title.equals(pk.title) && this.dateReleased == pk.dateReleased;
		}
		else {
			return false;
		}
	}
	
	/**
	 * this function returns an int generated by a hashing algorthim
	 */
	public int hashCode() {
		return (int)(this.title.hashCode() + this.dateReleased.hashCode());
	}
	
	/**
	 * this function returns a string with the title of an Album
	 * @return
	 */
	public String getTitle() {
		return this.title;
	}
	
	/**
	 * this function sets the title of an Album
	 * @param title
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	
	/**
	 * this function uses the gregorianCalendar to get the date released of an album
	 * @return
	 */
	public GregorianCalendar getDateReleased() {
		return this.dateReleased;
	}
	
	/**
	 * this function sets the date released of an album
	 * @param dateReleased
	 */
	public void setDateReleased(GregorianCalendar dateReleased) {
		this.dateReleased = dateReleased;
	}

}